#!/bin/bash

clear
echo -e "\e[1;31m"

echo -e "\e[0m"
mv /data/data/com.termux/files/usr/etc/bash.bashrc /data/data/com.termux/files/usr/etc/bash.bashrc_old
cp bash.bashrc /data/data/com.termux/files/usr/etc/bash.bashrc

apt-get update && apt-get upgrade -y
apt-get install fish  ncurses-utils proot proot-distro tsu fakeroot parted -y

clear

echo -e "\e[1;31m"
echo " ██▀███      ▒█████      ▒█████     ▄▄▄█████▓"
echo "▓██ ▒ ██▒   ▒██▒  ██▒   ▒██▒  ██▒   ▓  ██▒ ▓▒"
echo "▓██ ░▄█ ▒   ▒██░  ██▒   ▒██░  ██▒   ▒ ▓██░ ▒░"
echo "▒██▀▀█▄     ▒██   ██░   ▒██   ██░   ░ ▓██▓ ░ "
echo "░██▓ ▒██▒   ░ ████▓▒░   ░ ████▓▒░     ▒██▒ ░ "
echo "░ ▒▓ ░▒▓░   ░ ▒░▒░▒░    ░ ▒░▒░▒░      ▒ ░░   "
echo "  ░▒ ░ ▒░     ░ ▒ ▒░      ░ ▒ ▒░        ░    "
echo "  ░░   ░    ░ ░ ░ ▒     ░ ░ ░ ▒       ░      "
echo "   ░            ░ ░         ░ ░              "
echo -e "\e[1;33m                                 ROOT TERMUX"
echo -e "\e[1;32m                                 By Some Random Kid That Thinks He's Cool"

echo -e "\e[1;36m\n"
echo '[*] "Automation" started'
sleep 1
echo "Pretending to do stuff..."
sleep 0.5
echo "Pretending to do stuff..."
echo "Pretending to do stuff..."

echo "[*] DONE"

sleep 1.5
echo -e "\n\n\e[0mHit ENTER to continue..."
read

clear
termux-reload-settings
echo -e "TYPE \e[1;32mroot\e[1;34m WHENEVER YOU WANT ROOT PRIVILEGES\n\n"

